{
 "title": "Thriving.dev demo side-by-side 'internal.leave.group.on.close'",
 "time": { "from": "now-90s", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "Replicas",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(kafka_stream_alive_stream_threads{client_id=~\"kstreams-stateless-logger-.*\"})",
     "legendFormat": "active"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(kafka_stream_alive_stream_threads{client_id=~\"logger-leave-group-.*\"})",
     "legendFormat": "active"
    }
   ]
  },
  {
   "title": "Rebalances",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "idelta(kafka_consumer_coordinator_rebalance_total{instance=~\".*kstreams-stateless-logger-1.*\"}[10s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rebalances",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "idelta(kafka_consumer_coordinator_rebalance_total{instance=~\".*logger-leave-group-1.*\"}[10s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer Lags",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "max by(redpanda_topic, redpanda_partition)(redpanda_kafka_max_offset{redpanda_namespace=\"kafka\"}) - on(redpanda_topic, redpanda_partition) group_right max by(redpanda_group, redpanda_topic, redpanda_partition)(redpanda_kafka_consumer_group_committed_offset{redpanda_group=\"kstreams-stateless-logger\"})",
     "legendFormat": "{{redpanda_group}}::{{redpanda_topic}}[{{redpanda_partition}}]"
    }
   ]
  },
  {
   "title": "Consumer Lags",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "max by(redpanda_topic, redpanda_partition)(redpanda_kafka_max_offset{redpanda_namespace=\"kafka\"}) - on(redpanda_topic, redpanda_partition) group_right max by(redpanda_group, redpanda_topic, redpanda_partition)(redpanda_kafka_consumer_group_committed_offset{redpanda_group=\"logger-leave-group\"})",
     "legendFormat": "{{redpanda_group}}::{{redpanda_topic}}[{{redpanda_partition}}]"
    }
   ]
  },
  {
   "title": "Topic Log End Offset Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(redpanda_topic)(rate(redpanda_kafka_max_offset{redpanda_namespace=\"kafka\", redpanda_topic=\"random-numbers\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}