{
 "title": "New dashboard",
 "time": { "from": "now-3m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "Replicas",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(kafka_stream_alive_stream_threads)",
     "legendFormat": "active"
    }
   ]
  },
  {
   "title": "Consumer Lags",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "max by(redpanda_topic, redpanda_partition)(redpanda_kafka_max_offset{redpanda_namespace=\"kafka\"}) - on(redpanda_topic, redpanda_partition) group_right max by(redpanda_group, redpanda_topic, redpanda_partition)(redpanda_kafka_consumer_group_committed_offset)",
     "legendFormat": "{{redpanda_group}}::{{redpanda_topic}}[{{redpanda_partition}}]"
    }
   ]
  },
  {
   "title": "Topic Log End Offset Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(redpanda_topic)(rate(redpanda_kafka_max_offset{redpanda_namespace=\"kafka\", redpanda_topic=\"random-numbers\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}